### ISSUE TITLE
Simple example of use ?

### ISSUE THREAD

**Issue by daweedm** [ingoncalves/escpos-xml#1]
Hello,
It seems to an interesting project but I can’t figure out how to make it work for a simple template.
Would you add an example of use in the repo ?

Thanks a lot !

**Comment by ingoncalves** [comment]
Hello, I'm sorry for the lack of documentation. I did not have time to do
this yet. Tomorrow, I'm gonna to write a code example and push it to
repository.

Thanks for the contact!

Em Dom, 21 de jan de 2018 04:12, Daweed <notifications@github.com> escreveu:

**Comment by ingoncalves** [comment]
I've updated the Readme.md. It's not perfect yet, but will certainly help you.
Be free to help us!
Best regards.

**Comment by daweedm** [comment]
Thank you very much !
