### ISSUE TITLE
Print Table

### ISSUE THREAD

**Issue by VyankeshH** [ingoncalves/escpos-xml#10]
@ingoncalves Did you made template for the table printing?
Thank you.

**Comment by mtahir08** [comment]
@VyankeshH Did you get any solution?

**Comment by VyankeshH** [comment]
@mtahir08  No,Still no get.Did you try for the QRCode???Working or not?????

**Comment by mtahir08** [comment]
yes I just used QRCode and BarCode in the example and it is working.

**Comment by ingoncalves** [comment]
@VyankeshH to print tables, you may use the package [table](https://www.npmjs.com/package/table) to assemble your information in table format, and after that, you'll have a plain string to print via `<text-line>`. Hope this helps!

**Comment by VyankeshH** [comment]
@ingoncalves  I tried what you say but I didn't get result.So,did you have sample code for this???

**Comment by mtahir08** [comment]
@ingoncalves Thanks man (Y) it works for me.
@VyankeshH here is sample 

import {
  table, 
  getBorderCharacters
} from 'table';
 let arr,
    output;
 arr = [
    ['0A', '0B', '0C'],
    ['1A', '1B', '1C'],
    ['2A', '2B', '2C']
];
const options = {
        border: getBorderCharacters(`void`),
        columns: {
            0: {
                width: 5
            },
            1: {
                width: 2
            },
            2: {
                width: 3
            },
        }
    }
 output = table(arr, options);
 console.log(output);
 const xml = `
    <?xml version="1.0" encoding="UTF-8"?>
    <document>
    <text-line>{{output}}</text-line>
    </document>
    `
    const data = {   output   }
   const  printString = EscPos.getBufferFromTemplate(xml, data);

**Comment by VyankeshH** [comment]
@mtahir08  not able to get border.Did you get border for table

**Comment by mtahir08** [comment]
If you want to get borders just removed below property from options object.
 border: getBorderCharacters(`void`),// it hides table borders

**Comment by VyankeshH** [comment]
@mtahir08 I know brother.Even I got it on console but I doesn't got it on printer

**Comment by ingoncalves** [comment]
@VyankeshH you must check which characters you printer supports. Probably, the character used to make the border is not supported. Try setting the border character to a character that you are sure that the printer supports.

**Comment by VyankeshH** [comment]
@ingoncalves Ok brother.
Thank You ; )

**Comment by ingoncalves** [comment]
I'll close it, but If you have any question, please feel free to ask us.

**Comment by ikbalmoh** [comment]
I used the table package with escpos-xml, working fine on debugging mode. 
But I got error when not connect to debugger 
`undifined is not a function (evaluating 'str.normalize()')`

I realize that this problem is not related to this package, Hope someone could help
