### ISSUE TITLE
Electrode ReduxRouterEngine Error: TypeError: Cannot read property 'refreshOnCheckAuth' of undefined

### ISSUE THREAD

**Issue by VyankeshH** [ingoncalves/escpos-xml#24]
I am getting above error on loading page 
`//
// This is the client side entry point for the React app.
//

import React from "react";
import { render } from "react-dom";
import { routes } from "./routes";
import { Router, browserHistory } from "react-router";
import { createStore, applyMiddleware } from "redux";
//import { createStore } from "redux";
import { Provider } from "react-redux";
import { createLogger } from "redux-logger";
import { notify } from "react-notify-toast";
import "./styles/base.css";
import rootReducer from "./reducers";
import { showSpinner } from "./actions";
import { sessionService } from "redux-react-session";
import thunk from "redux-thunk";
import * as sessionApi from "./api/sessionapi";
require.ensure(["./sw-registration"], (require) => {
  require("./sw-registration")(notify);
}, "sw-registration");
/**/

const validateSession = (session) => {
  // check if your session is still valid
  return true;
}
const renderApp = (store) => {
  const showSpinnerOnLoad = () => {
    store.dispatch(showSpinner());
  };
  render(
    <Provider store={store}>
      <Router history={browserHistory} >{routes(showSpinnerOnLoad)}</Router>
    </Provider>,
    document.querySelector(".js-content")
  );
};
window.webappStart = () => {
  const initialState  = window.__PRELOADED_STATE__;
  const middleware    = applyMiddleware(thunk, createLogger());
  const store         = createStore(rootReducer, initialState, middleware);

  //const store = createStore(rootReducer, initialState);
  sessionService.initSessionService(store,
    { refreshOnCheckAuth: true, redirectPath: "/login", driver: "COOKIES",validateSession });
  sessionApi.login().then(response => {
    const { token } = response;
    if (token === 0) {
      renderApp(store);
    } else {
      sessionService.saveSession({ token })
        .then(() => {
          sessionService.saveUser(response.data);
          renderApp(store);
        }).catch(err => err);
    }
  });
};
`

//package.json
{
  "name": "ivdashboard",
  "version": "0.0.1",
  "description": "IVCargo Dashoboard ",
  "homepage": "",
  "author": {
    "name": "Mitesh",
    "email": "mitesh@ivgroup.in",
    "url": ""
  },
  "contributors": [
    "Mitesh"
  ],
  "files": [
    "server",
    "client",
    "test"
  ],
  "main": "server/index.js",
  "keywords": [
    "Dashoboard",
    "Ivcargo"
  ],
  "repository": {
    "type": "git",
    "url": "miteshivgroup/ivdashboard"
  },
  "license": "ISC",
  "engines": {
    "node": "^4.x.x || ^6.x.x || ^7.x.x",
    "npm": ">= 3.x.x"
  },
  "scripts": {
    "prestart": "gulp build",
    "start": "if test \"$NODE_ENV\" = \"production\"; then npm run prod; else gulp dev; fi",
    "test": "gulp check",
    "coverage": "gulp check",
    "prod": "echo 'Starting standalone server in PROD mode' & SET NODE_ENV=production & node ./lib/server/",
    "heroku-postbuild": "gulp build"
  },
  "dependencies": {
    "@ag-grid-community/all-modules": "^22.0.0",
    "@ag-grid-community/react": "^22.0.0",
    "@material-ui/core": "^3.9.2",
    "babel-plugin-transform-node-env-inline": "^0.1.1",
    "bluebird": "^3.5.0",
    "boom": "^5.2.0",
    "chart.js": "^2.6.0",
    "core-js": "^3.4.7",
    "electrode-archetype-react-app": "^3.1.6",
    "electrode-confippet": "^1.5.0",
    "electrode-csrf-jwt": "^1.2.1",
    "electrode-react-ssr-caching": "^0.1.6",
    "electrode-react-webapp": "^1.7.2",
    "electrode-redux-router-engine": "^1.4.5",
    "electrode-server": "^1.2.2",
    "electrode-static-paths": "^1.1.0",
    "events": "^1.1.1",
    "get-parameter": "^1.0.8",
    "lodash": "^4.17.4",
    "material-ui": "^0.18.6",
    "moment": "^2.24.0",
    "query-string": "^4.3.4",
    "react": "^15.6.2",
    "react-chartjs-2": "^2.5.3",
    "react-dom": "^15.6.2",
    "react-flexboxgrid": "^1.0.1",
    "react-html-table-to-excel": "^2.0.0",
    "react-notify-toast": "^0.3.0",
    "react-select": "^2.4.4",
    "react-tap-event-plugin": "^3.0.3",
    "redux-logger": "^3.0.6",
    "redux-react-session": "^2.6.0",
    "redux-thunk": "^2.2.0",
    "require-at": "^1.0.0",
    "wreck": "^12.2.2",
    "xclap": "^0.2.39",
    "xsh": "^0.3.7"
  },
  "devDependencies": {
    "electrode-archetype-react-app-dev": "^3.1.6",
    "gulp": "^3.9.1"
  }
}

**Comment by VyankeshH** [comment]
Electrode ReduxRouterEngine Error: TypeError: Cannot read property 'refreshOnCheckAuth' of undefined
    at Object.checkAuth [as onEnter] (E:\IVWorkspace\ivdashboard\node_modules\redux-react-session\dist\index.js:169:42)
    at Array.transitionHook (E:\IVWorkspace\ivdashboard\node_modules\react-router\lib\TransitionUtils.js:48:12)
    at E:\IVWorkspace\ivdashboard\node_modules\react-router\lib\TransitionUtils.js:119:19

**Comment by ingoncalves** [comment]
Issue not related to the `escpos-xml` project. Closing.
