### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by lakshmajee** [ingoncalves/escpos-xml#25]
I'm interested in this library. Is this library still maintained by someone?
Or do we have any fork that is in a good (not strictly) state?

**Comment by ingoncalves** [comment]
Unfortunately, I am no longer maintaining this lib. But you can find some forks that may work for you.

**Comment by lakshmajee** [comment]
Oh, Thank you @ingoncalves . I will look into another

**Comment by augustosnk12** [comment]
which fork is the most maintained?
