### ISSUE TITLE
Loop in template

### ISSUE THREAD

**Issue by mtahir08** [ingoncalves/escpos-xml#8]
I want to use loop in template format. 
Can anyone please tell me how it will achieve.
Thanks #

**Comment by ingoncalves** [comment]
The template uses the [handlebars.js](https://handlebarsjs.com/) engine. So, can use the [each](https://handlebarsjs.com/builtin_helpers.html) clause to achieve that.

**Comment by mtahir08** [comment]
Thanks it works with each.
